version: '3'

services:

  postgres:
    image: postgres:14.2
    restart: always
    env_file:
      - variables.env

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379"

  application:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    restart: always
    env_file:
      - variables.env
    volumes:
      - static_files:/code/api/static
    depends_on:
      - postgres
      - redis


  celery_worker:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    restart: always
    env_file:
      - variables.env
    depends_on:
      - postgres
      - redis
    command: celery -A api worker -l INFO

  celery_beat:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    restart: always
    env_file:
      - variables.env
    depends_on:
      - postgres
      - redis
    command: celery -A api beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

  nginx:
    restart: always
    depends_on:
      - application
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - static_files:/opt/static

volumes:
  pg_data: {}
  static_files: {}

