version: '3'

services:

  postgres:
    image: postgres:14.2
    restart: always
    env_file:
      - variables.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432"

  redis:
    image: redis:6.2
    restart: always
    ports:
      - "6379"

  application:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    restart: always
    env_file:
      - variables.env
    volumes:
      - ./src/:/code/
    links:
      - postgres
      - redis
    ports:
      - "8888:80"
    command: tail -f /dev/null


  worker:
    build:
      context: .
      dockerfile: ./docker/application/Dockerfile
    restart: always
    working_dir: /code/api/
    env_file:
      - variables.env
    volumes:
      - ./src/:/code/
    links:
      - postgres
      - redis
    command: celery -A api worker -l INFO


volumes:
  pg_data: {}
  static_files: {}

