# Generated by Django 4.0.4 on 2022-04-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_code', models.CharField(choices=[('USD', 'Usd'), ('BTC', 'Btc')], max_length=3)),
                ('to_code', models.CharField(choices=[('USD', 'Usd'), ('BTC', 'Btc')], max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=15)),
                ('bid_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('ask_price', models.DecimalField(decimal_places=8, max_digits=15)),
                ('refresh_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
