# Generated by Django 3.2.13 on 2022-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='currencyexchangerate',
            index=models.Index(fields=['from_code', 'to_code'], name='core_curren_from_co_c9ad57_idx'),
        ),
    ]
